[[fortran_expansion]]
arch = "i686"
git-tree-sha1 = "e6c0497705334d35a7d3675ee6f13ee897e5dad5"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "4ab14c83cdb9968eaf1e4827342a052180e623555e965fa58385289caba5eb6d"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.i686-linux-gnu-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "armv7l"
git-tree-sha1 = "1986a5a3fba5b4d16cc94897e101cb944ad87703"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "0d7301b3805855daf925371112f95b8f509015707f6a6e0c5dc48e0186794f38"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.arm-linux-musleabihf-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "e6505881c9bdffd1765e97a7c5bd5a4e9fa3d64e"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[fortran_expansion.download]]
    sha256 = "5bb02a617213c1e83d944bde80f9621f8ded05294f4769f750ab9494911f8d17"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "i686"
git-tree-sha1 = "2da826a2f1ea81e194236760f7a7df04f22f29ed"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "4f9b302b75b98b617ab6f620ce1015c27563bedbde968137969c8455f72cb763"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.i686-linux-gnu-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "aarch64"
git-tree-sha1 = "9294d3bc980ff1272e245a718f7a6a1fa9fc5b24"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "cbd40a9edbf7ad9ff70370a9ca24aa39a2f36b4dc7f2d4a5c39c15076959acc6"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.aarch64-linux-gnu-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "aarch64"
git-tree-sha1 = "596faa307041ee397373a1e7ee8f511b8ee11344"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "3f30329297d1fb14342ac3afc6d4dada6a321e0579532ad7ec19c8970602c1e0"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.aarch64-linux-musl-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "e33201c225ce4ee9ce3b9a840e43470320744f44"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "4c2e06d7b1c60e39baf07010cc3787ecb3be767c30573396d614117b2a6742c2"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-linux-gnu-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "aarch64"
git-tree-sha1 = "603c259ed0947531cfc278fc870709f3c36408d3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "10d17c6fde1053b80c5d7d8130f7642ad82f79bec2bcb42a622d2f61529e880e"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.aarch64-linux-gnu-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "i686"
git-tree-sha1 = "480270ba6a5f14a95ab7c440d194d1b848ba3d1f"
libgfortran_version = "4.0.0"
os = "windows"

    [[fortran_expansion.download]]
    sha256 = "ca11b8a30bd6709d567759838a1a6a683ff4bf2fc2d5570ff890ffba4e9f1197"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.i686-w64-mingw32-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "i686"
git-tree-sha1 = "409099b8095b507663e5016217a2249970e64beb"
libgfortran_version = "5.0.0"
os = "windows"

    [[fortran_expansion.download]]
    sha256 = "8e4146f9f5422738f5456e99991047a513a040bc4de1d39439af0142643695e3"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.i686-w64-mingw32-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "i686"
git-tree-sha1 = "96689068528b59e7d51da0bd503e926c19a84cae"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "c7ea5a56c2e61449d885fd5983444b9044064380d065b80f0f3a11b34e6f590a"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.i686-linux-gnu-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "61f795896fe2a773da4d4f7a40d45bfb87d5281e"
libgfortran_version = "3.0.0"
os = "windows"

    [[fortran_expansion.download]]
    sha256 = "78e8027bac01388b9a8d10a5ccdd826c343d83099e33cb86faca2cbdde26cde9"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "de7fa2a8c2ee06754a0c5aaaef405a0ea6cc2b08"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "405bfd4da16d5c6d70747f7a48f6682333c2997199141b7511bab5e9ecf974a3"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-linux-gnu-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "i686"
git-tree-sha1 = "43e47d8b0c5b7b7bc4562c2d00b84ad32216e922"
libgfortran_version = "3.0.0"
os = "windows"

    [[fortran_expansion.download]]
    sha256 = "d281786cc5203a166aa3476497987ebb620f21d2ca74a733610473ad94c4c84b"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.i686-w64-mingw32-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "aarch64"
git-tree-sha1 = "d7e5bafbf62d1f7a9ea5481852900a2db25703db"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "018cf8b0954ce1b9fedf7aca59e8269f3d33b9d6663b3f5e9cbf1519e321eddf"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.aarch64-linux-gnu-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "957a1d19d2b79a4f30ee6a36865fbc0e81f5362e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "9bec6ea54fdb92f9bc301efb35f39e334626d5525553ad70b0114c041447673b"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-linux-gnu-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "i686"
git-tree-sha1 = "a96bc7f0088c765a6506e7f0fd20320ad689481f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "6ef785716ca8bf869488b889e9cf4c333962b9cecac19844e332a552aa628943"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.i686-linux-musl-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "aarch64"
git-tree-sha1 = "6e738921b799478b8eb64a314e3f9a26548bd072"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "6837a123ccf4b0dacf7114a0136171eab22ec1789e54bfbfdf65040ada7382de"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.aarch64-linux-musl-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "armv7l"
git-tree-sha1 = "a5b60d5c8e0dd16077339bcd6e74a95fbb26ae79"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "43ed654223caf8662bbc1a5d12c4e5abe5c97cb2049d38b9a2007dfa7faa1f1c"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.arm-linux-gnueabihf-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "powerpc64le"
git-tree-sha1 = "577ff09aaf5d78d0429e967e3c14ca8f3ea5c3cc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "a19ebb96e9ae0abcac49508fb6a3f108c63421721376f5a3951f4f3657119589"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "aarch64"
git-tree-sha1 = "bbc6e0f961fb4df227807841d19887987c9b8434"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "b359945302f800b985f97ad92b680804dcae468fb94cec3676930ce9b16108c6"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.aarch64-linux-musl-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "armv7l"
git-tree-sha1 = "6dd5fc99e91ca58c51de6f5f28efdc3b26fb3e81"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "7d51d812d6367021b59b1360d5683a92b9e006312e6c89a52927f693d3faca69"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.arm-linux-musleabihf-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "armv7l"
git-tree-sha1 = "fbb3b9154ba933d69dd8635d7929ea50b261ae6b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "fe872d99464569714c145da4b56dbe8a3663f16b80fa64061983b3752eb0b58e"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.arm-linux-musleabihf-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "50f1b6478cbd82a7e6da6318c67ea1ade8187b75"
libgfortran_version = "5.0.0"
os = "macos"

    [[fortran_expansion.download]]
    sha256 = "56095cf8ab3247177f306ebc82a155db1efae67519610bf748b338940f8fd030"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "c4e3a1239258750886b917ba5ff330009c5ea1ce"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "a52059fa84376335366b05c8eb22a7e6d8343df5cfe0228387a6dbd2db390c86"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-linux-musl-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "1aa28a3989aff7ce3fc7439ee9e2862e79d03853"
libgfortran_version = "3.0.0"
os = "macos"

    [[fortran_expansion.download]]
    sha256 = "f8e0316dba4e2f2524649e908b84146c861b5361a453d26dc901b330367fdec7"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "6ebce4273a3610fe222d7c290bb9e83ed1d53682"
libgfortran_version = "5.0.0"
os = "windows"

    [[fortran_expansion.download]]
    sha256 = "f660a32376f994a104331685ff10be7862693729b8c0a91aac22e5947ec03ff2"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "906f32a931a84062d49b3ae94d7011ad1f5858db"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "d8de37af45b88593d2d29b6427b378d2129c0cd6876572cee2cec679f31fce19"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-linux-musl-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "i686"
git-tree-sha1 = "ef91fa8f57f448af52b61506034dab1bd064973d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "e75c8f94101063d52732b4d97caeb61db802dd45977fc25f07b1ebbbd270083d"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.i686-linux-musl-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "21a93551fe408778fb69d0edce5259242b96da47"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "a6ca7d2ca23ae9febbfbf2ccb1c42da62f1a19bc0cbcb3938c0778b4fdeb6528"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-linux-musl-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "d6ec8d68cc76c186c33be951b09296722328cbb7"
libgfortran_version = "4.0.0"
os = "windows"

    [[fortran_expansion.download]]
    sha256 = "936adbb239a0d657be677778864a1323ccd09350a812e31021e493dc7e79a8b9"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "569566b89761317ff14627b9fc335d3e472a5b3f"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[fortran_expansion.download]]
    sha256 = "8f48b816db7889e593ab12e5252322a2f84469567968a9470cb89546393fc8da"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "powerpc64le"
git-tree-sha1 = "0f05c2feca760f8ddd43f3271b552795104c0a21"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "6a18cb51d1b98ab2d3a5e30e9e6d02b5284107164a3837ba35a2c418c4b78d5a"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "i686"
git-tree-sha1 = "d8b0d5b871870fac0e1c4b8341c83998a45f83e2"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "f792b714a8c55229a1f3631ac8888251725437b3df7d2094e50fa6cb75c56d3d"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.i686-linux-musl-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "9b51cfe4b81013b9212fd3be6c6b44069b8bb413"
libgfortran_version = "4.0.0"
os = "macos"

    [[fortran_expansion.download]]
    sha256 = "a08c1c727d77faa5d10eeee0ed2e1226e6bba73892f8eb9817b4062f2af7c889"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "armv7l"
git-tree-sha1 = "2f044063ed18e12b5ccbba7e68c7526bc8395252"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "015fcb65840bfa72166e26a0eea9df0bc2cac12ad487a86a6cdd298678484be4"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.arm-linux-gnueabihf-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "armv7l"
git-tree-sha1 = "eef686f92e7acc64be597b1b201a59dc063bf211"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "cf1e5f3419f11279681c097723c1d42ade46ba63590e079d709be03ab4d17488"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.arm-linux-gnueabihf-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "powerpc64le"
git-tree-sha1 = "3c4973b2ac276c2152cdd17f84d81ab8f4916202"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "273d06da777d2083a65f086e754a3c6b22a58a42d3b7b8431d1e2c0220813b54"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "5dfb46aa9a9573198743516bc2fdfd012447fdf4"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[fortran_expansion.download]]
    sha256 = "1490583599d06b0541d8a817a74d2719f22560b1cbf1973874148fb19f81e4e8"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
