[[fortran_expansion]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "904a31df4833dae5ad14ecf51bb96f2d14246315"
libc = "glibc"
libgfortran_version = "5.0.0"
libstdcxx_version = "3.4.26"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "ddc3287dcd79af14731430ccfdb1d69eec2274cd055b705b52596067570c715d"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-linux-gnu-libgfortran5-libstdcxx26-cxx11.tar.gz"
[[fortran_expansion]]
arch = "aarch64"
git-tree-sha1 = "4425a42f70dc1f2db88f0d7e22f5d9da1e054a7b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "e620d355515287ee877d322fe9ec42b3e3d7354a2edac0004bef299e8d8bc467"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.aarch64-linux-gnu-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "armv7l"
git-tree-sha1 = "83762ea7100562991f10f311f50492d5a5ebd4e8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "27dca21b947edb47dbec73fcab0aeb7bde5b1e39514c233c5e63cc19aa63843e"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.arm-linux-gnueabihf-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "i686"
git-tree-sha1 = "0d837eef2617ed9da0a12f5b517e20ee2b869aa0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "907fb6eba2cdefaea1bb4de5084db7785e2497a726a63dbfc08e50b74f7a1632"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.i686-linux-musl-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "e89e8f2e73de9285d3092f5bed22b81fedcc0cea"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "3683c6d81b6afabb549d2d66cc3dc6d8cf33d9c0d7d8018d12f32640ce3df1b4"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-linux-musl-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "i686"
git-tree-sha1 = "8336a7ab9a2b9b2c7ca49b12a946875e4ec9fb76"
libgfortran_version = "3.0.0"
os = "windows"

    [[fortran_expansion.download]]
    sha256 = "56ae39afd33212c45a4e056de968fdf16536eb15981e18feacaac35969ecf305"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.i686-w64-mingw32-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "96c7cf163c42ae793206c7283b770ebcaf920cbd"
libgfortran_version = "3.0.0"
os = "windows"

    [[fortran_expansion.download]]
    sha256 = "bef8e957164e35745454ff6f43ae2bf3669e941af6f907e46fc491bad516fda8"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "powerpc64le"
git-tree-sha1 = "49e4e68fd977230ad4a84236852f89a22eeeee41"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "bb4f42345a74ac9cf416b62b97c8e6c44d7ab7247c65730f329b2478877b1eb4"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "aarch64"
git-tree-sha1 = "fd2e67fe437fe7fdb61b7d8883b8fc86712fd42a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "0cb695d322f9cbb033ae8571ce07907b3e7aa4663535ed7565fca379a3d178f9"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.aarch64-linux-gnu-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "867aa577bedb7a0b0d386b8d660e8b089e82d3b0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "79639d7a6b8bf92b5ab4c9c3fd3a0b0b2cebb5097a78070f367b285ae67f16db"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-linux-gnu-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "aarch64"
git-tree-sha1 = "7df2ab153c6df8a7fab34bb93c0579712ac68643"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "af7a0bb578ea99c2433643300e4f09682eeb68c3bddb0543730ec49ca6e1c3c4"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.aarch64-linux-musl-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "4bffec151113d14fc63ddd93ec0a01b8e08ec266"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[fortran_expansion.download]]
    sha256 = "66106156be431a4bbeab7418feb59c41660e313b178ced072c8a31b4ec672a0e"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "i686"
git-tree-sha1 = "f421798c5d94be71e61d6d8d6b655f3dfed0e25a"
libgfortran_version = "4.0.0"
os = "windows"

    [[fortran_expansion.download]]
    sha256 = "33ad53afa2a6cb6df409950048a469c203d70e40f0042e702a1d9a4c82e14844"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.i686-w64-mingw32-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "4fd87c07435de3e7c8aa7cd87fd048b2874ed1fc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "9e45bda7f489d4ccb2d2c584473461892eb1626ce67f68f9e04b1e6fff845fbd"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-linux-gnu-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "aarch64"
git-tree-sha1 = "1c153b565883f7de108f45deaa2c15460ba52fcb"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "5be86f1ad2266888637960507953f588c0b0d95b4ca016240df39ff8e1548b6c"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.aarch64-linux-gnu-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "armv7l"
git-tree-sha1 = "f16556f858a230692b4ad93e17f8249624e3f3c7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "4704ee785f0fd84d3af70919d3ccb6156196d8818a113373d691fee5c8a0c05f"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.arm-linux-gnueabihf-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "c1cea1bd93dd1beb0e2baef6cb46314030e351e2"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[fortran_expansion.download]]
    sha256 = "d3ade4279bae8314a8807b663eb83ddb1f58675e901fd469a7fddc3d5675465b"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "aarch64"
git-tree-sha1 = "5903d508104634a1752ff78e7eeafe9de7064e27"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "025bd6298795b2f549e285340c32950bb337db8942150a42d684dbbaf45b74ce"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.aarch64-linux-musl-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "6d0e363eef031dabeb594196359549df5907e5be"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "e0f5a1d52524dfdd2aa4d38f71f602bd3ae24b5e7a73a838ad90f16b1956415f"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-linux-musl-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "396ec029f34138f814c36c6414662f51f369bc4c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "40e99db99546784d10cf9e16b30069656e312cfcd7f8323e8d1d0bb487de3d48"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-linux-gnu-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "powerpc64le"
git-tree-sha1 = "ccd5c1161002d70a94d0468c0c4f366a031bc7bc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "e6ce3b77153da5ac76970beb0cc9058f3a3f4397dcb492792f363e3a9cc32e7d"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "5ec613094008cce3028dedc1b05bb35640bbb2fd"
libgfortran_version = "5.0.0"
os = "windows"

    [[fortran_expansion.download]]
    sha256 = "a100bfa54782d51c95f9ba8aefa113676cf31aa7aa2202f3b0139cb4c7eedb25"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "a08a3082e644b891a5e3021fe88dcd5a2d2c9812"
libgfortran_version = "5.0.0"
os = "macos"

    [[fortran_expansion.download]]
    sha256 = "4252f781e6476a426b548d2ddd269b1670818efdecfd367483396c655e2062d9"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "ff9c390a4a48ecb76ed23349de8dd2a5510e3c5d"
libgfortran_version = "4.0.0"
os = "macos"

    [[fortran_expansion.download]]
    sha256 = "313a221a0e75ce2abc529996b5f2f4548a50c86b5071a0f531b775fd666dccf8"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "2ee421869171e0bee8ecbb2b3a37dfe392b68f92"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[fortran_expansion.download]]
    sha256 = "abfc4e088db4917dfb5b8ce63e016b03de91915fa8b50ea56a264d02fdef8054"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "powerpc64le"
git-tree-sha1 = "274fb12d937d5848fac9fd88b88097627a8317b1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "a1ead511595621790226dee775374483c5bd612ea5d7b1e71731a94e787ca23e"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "i686"
git-tree-sha1 = "35f175d0c1e77f79be79c6af41977e9265529556"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "7c39b7a9f45b7398ab25631d678abdc409e29a3de2b92d8c6d59d6557d0adc64"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.i686-linux-gnu-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "2c0ae45b3ddd19f1c7721b781722ff1af069562f"
libgfortran_version = "3.0.0"
os = "macos"

    [[fortran_expansion.download]]
    sha256 = "3f3c8144a2bec4239c8fe657a8f79672f0c9de106f86c178f9bae1d95744b310"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "i686"
git-tree-sha1 = "bca6edaa812d2964efd0f4c02afe3532e8f0e925"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "8d4c1c9a8fdf522d6c81b90d8edebff20463664e2b952e8004ad5c22f657826f"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.i686-linux-gnu-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "i686"
git-tree-sha1 = "af19f1a56e52bb4d78618e9f3a70d7a527a83bba"
libgfortran_version = "5.0.0"
os = "windows"

    [[fortran_expansion.download]]
    sha256 = "9fd29f18c9e7f8391f14897c47d6b9563adf51728128020034539b1e47ad8838"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.i686-w64-mingw32-libgfortran5.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "7d31401b3f34e0f787c50c640df55ef52e28a058"
libgfortran_version = "4.0.0"
os = "windows"

    [[fortran_expansion.download]]
    sha256 = "c2db40d473434afaafea043ccd504faee27c1bf8a3a3189c77c903d379578e96"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "i686"
git-tree-sha1 = "76d4e3232efe3f40bb27e5da679d698e72861eb3"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "d2b8b2f03aad217457f2cd22be275a28e4eb967337226b79856fd270d2c28f2d"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.i686-linux-musl-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "armv7l"
git-tree-sha1 = "8be930e5cf694cf86fa9e2a55ee62d5b26867591"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "330edacbf3190fea06f18aa3f9259e6c9abe883e96d4e0d7b4402d5bc222227e"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.arm-linux-musleabihf-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "aarch64"
git-tree-sha1 = "370508bdbdb8d61842cb7b8a28a603f8370d7be7"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "123929be85486609be1f03f7f6d95f8edcf38195bc6df69bece5fc11eaa1a401"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.aarch64-linux-musl-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "x86_64"
git-tree-sha1 = "b6ed730848e77b7dc12bbea1ae4228a14b725a73"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "c1ccc6471d7e907e1ed0686996b79cbd54f04338ad7f3210ca39004d2fea6de3"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.x86_64-linux-musl-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "armv7l"
git-tree-sha1 = "4f2087e2073f7c031a73c4c9a6bb2a5fbf820fca"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "bb85fbebad09a0f4d2c89ffc3e2f22de227bf671e1e9b8ec8c03b9572cd8a576"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.arm-linux-gnueabihf-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "i686"
git-tree-sha1 = "bc4e4e05dc35bb4e30dd8d96007848a1ea935131"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "8940f9b5c05c062f0d767791d3f92cfdd93f1fa05e76edd22748692b70215257"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.i686-linux-gnu-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "armv7l"
git-tree-sha1 = "5ebf7c377a41699db9240dabad1006dbe1784c5e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "867ba70a613cdd4861437f9b97e009c015bc1a654ed8be51bfabe2ee7a5c6bc6"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.arm-linux-musleabihf-libgfortran4.tar.gz"
[[fortran_expansion]]
arch = "i686"
git-tree-sha1 = "fcdfa2170df212c0198071af88612ec3b4d6bd4b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "634bc42bbcbe766ec93c3dcc1dc3e44e39e3d083fa2aeacce6f1b8c3fe60021c"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.i686-linux-musl-libgfortran3.tar.gz"
[[fortran_expansion]]
arch = "armv7l"
git-tree-sha1 = "0b2bce1f27bf03a16db5e0e3b64964e5e47bc53a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[fortran_expansion.download]]
    sha256 = "ab5c98fbb6d90c32779cd0336fd93484f43502aaac06151de81ef062b57d8bcf"
    url = "https://github.com/JuliaBinaryWrappers/fortran_expansion_jll.jl/releases/download/fortran_expansion+v0.1.3+0/fortran_expansion.v0.1.3.arm-linux-musleabihf-libgfortran5.tar.gz"
